{% set version = "3.7-3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-plotrix
  version: {{ version|replace("-", "_") }}

source:
  fn: plotrix_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/plotrix_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/plotrix/plotrix_{{ version }}.tar.gz
  sha256: 8e9dc9e3130f20ebe11c1bbf753a3670660b382f3f0501ab293afaf58217e0a0

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('plotrix')"  # [not win]
    - "\"%R%\" -e \"library('plotrix')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=plotrix
  license: GPL (>= 2)
  summary: Lots of plots, various labeling, axis and color scaling functions.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
